version: "3"

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
  spring:
    build: .
    restart: always
    ports:
      - 80:8080
    depends_on:
      - mysqldb
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/testdb
      SPRING_DATASOURCE_USERNAME : root
      SPRING_DATASOURCE_PASSWORD : 1234
  redis:
    image: redis:alpine

    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379


