spring:
  jpa:
    hibernate:
      ddl-auto: create
#    generate-ddl: true
#    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: redis
    port: 6379