spring:
  jpa:
    hibernate:
      ddl-auto: create
#    generate-ddl: true
#    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1234